name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./app1-frontend
          push: true
          tags: ghcr.io/orrg3nt/projet-devsecops/frontend:latest

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./app2-backend
          push: true
          tags: ghcr.io/orrg3nt/projet-devsecops/backend:latest

      - name: Deploy to k3s via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            kubectl apply -f /PROJET_DEVSECOPS/PHASE_1_DEV/k3s_minimal/
